version: '3.1'
services:
  web:
    container_name: ${WEB_HOST}
    image: ${WEB_IMAGE_NAME}
    env_file:
      - .env
    depends_on:
      - db
      - pgadmin
    ports:
      - "${WEB_PORT}:8069"
      - "${WEBSOCKET_PORT}:8072"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./:/etc/odoo
      - ./addons:/mnt/extra-addons
      - ./init-script.sh:/init-script.sh
      - ./init-db.sql:/init-db.sql
    user: root
    entrypoint: /bin/bash -c "chmod 644 /etc/odoo/.env && chmod +x /init-script.sh && /init-script.sh"
volumes:
  odoo-web-data: